[package]
name = "addsubs"
version = "1.1.3"
edition = "2021"


[profile.release]
strip = true # Automatically strip symbols from the binary
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
